# This cluster role enables manipulation of Knative services
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkerd-ts
rules:
- apiGroups:
  - split.smi-spec.io/v1alpha2
  resources:
  - trafficsplit
  verbs:
  - get
  - list
  - create
  - patch
  - update
  - delete